name: Sync

on:
  workflow_dispatch:

jobs:
  SyncAndMerge:
    name: Sync master and merge develop
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4.1.1
        with: 
          ref: develop
          fetch-depth: '0'
      - name: commands
        run: |
          git checkout master
          git merge origin/develop --ff-only
          git push https://x-access-token:${{ secrets.TEST_TOKEN }}@github.com/Compy-testing/AMDMIGraphX.git HEAD:master
